# Generated by Django 4.2.7 on 2023-11-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipament_name', models.CharField(max_length=250)),
                ('lab_name', models.CharField(max_length=250)),
                ('patrimony', models.IntegerField()),
            ],
        ),
    ]
