# Generated by Django 4.2.7 on 2023-11-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipamet',
            new_name='Equipament',
        ),
    ]
